INSERT OR REPLACE INTO products (id, slug, name, category, kind, price_cents, interval, summary, description, href, featured, sort_order) VALUES
('p-adhealth', 'ad-health', 'AD Health', 'app', 'subscription', 4900, 'month',
 'Active Directory health: controllers, replication, DNS, SYSVOL.',
 'Hosted ops app for domain controller health, replication, DNS, and SYSVOL. Starting list price. Access is provisioned to the Google account used at checkout.',
 NULL, 1, 110),
('p-netadmin', 'netadmin', 'Netadmin', 'app', 'subscription', 3900, 'month',
 'Network inventory, device status, and change tracking.',
 'Network administration workspace for the gear you already run — inventory, reachability, and a record of config changes. Starting list price. Access follows the Google account on the order.',
 NULL, 1, 120),
('p-sysadmin', 'sysadmin', 'Sysadmin', 'app', 'subscription', 3900, 'month',
 'Server inventory, patch posture, and day-to-day ops tasks.',
 'Systems administration console for Windows and Linux hosts: inventory, patch posture, and the operational tasks you repeat. Starting list price. Tied to the checkout Google account.',
 NULL, 1, 130),
('p-launcher', 'launcher', 'Launcher', 'app', 'subscription', 1500, 'month',
 'One signed-in place to open the apps you own.',
 'A launcher for the custom apps on this store. After checkout, the Google account sees the tools that account is entitled to. Starting list price.',
 NULL, 1, 140),
('p-projects', 'project-management', 'Project Management', 'app', 'subscription', 2900, 'month',
 'Engagements, milestones, and client work in one board.',
 'Project board for consulting engagements: milestones, owners, and status you can show a client. Starting list price. Access is the Google account used to order.',
 NULL, 1, 150),
('p-reports', 'reporting-engine', 'Reporting Engine', 'app', 'subscription', 3900, 'month',
 'Scheduled operational and executive reports.',
 'Reporting workspace for the ops data you already collect — scheduled summaries and executive-ready output. Starting list price. Provisioned to the checkout Google account.',
 NULL, 1, 160);
